apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: myapp
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: APP_ENV
              value: staging
            - name: AWS_REGION
              value: us-east-1
            - name: APP_PRICING_SERVICE_BASE_URL
              value: http://pricingapp
